version: '3.5'

services:

  soc-media-api_db:
    container_name: soc-media-api_db
    domainname: soc-media-api
    image: postgres
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soc-media-api_db
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"